### ISSUE TITLE
How to work with multiple production environments?

### ISSUE THREAD

**Issue by jaydenseric** [zeit/now-env#10]
All of the examples available here and in Next.js assume only 2 environments, local and production. I'm 100% invested in the Zeit ecosystem (Next.js, Now) yet can't work out an elegant solution to this typical use case:

- Local development, deployed staging and production environments.
- Local environment can override *any* env vars (`NODE_ENV`, `PORT`, `DB_URI`, etc.) but has defaults for all. Can tap into Now secrets.
- Production environment should be able to be configured and run locally, to test things like bundle sizes. This means it can't be assumed Now is loading the env vars for the build and start scripts.
- Staging deployments use staging Now secrets for certain variables (`DB_URI`).
- Production deployments use production Now secrets for certain variables (`DB_URI`).
- Next.js configured to use `babel-plugin-transform-inline-environment-variables`. The `next build` npm script needs to have the env vars loaded first.

For the last point, (simplified) my npm scripts look like this:

```json
{
  "scripts": {
    "build": "dotenv next build",
    "start": "dotenv next start",
    "deploy:staging": "now --local-config now.staging.json",
    "deploy:production": "now --local-config now.production.json"
  }
}
```

The `dotenv` coming from [`dotenv-cli`](https://www.npmjs.com/package/dotenv-cli).

This setup does not allow Now secrets in local env vars.

How can we get `now-env` to work for the above requirements? Does it need to be enhanced to work like `dotenv-cli`; with a bin entry and CLI API?

**Comment by sergiodxa** [comment]
Well now-env is only intended for development usage, you can send a PR to implement a CLI way to define the now.json file name to let you use many files.

But remember this is intended for development, so in staging you can use another now.json with different secret names while deploying to Now and use the default now.json for production deployments.

**Comment by sergiodxa** [comment]
This can now be done using NOW_CONFIG to define where to find the now.json allowing multiple config files.
